let pokedex = [
    {
        "id":1,
        "nombre":"bulbasaur",
        "tipo": ["planta", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png"
    },
    {
        "id":2,
        "nombre":"ivysaur",
        "tipo":["planta", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png"
    },
    {
        "id":3,
        "nombre":"venusaur",
        "tipo":["planta","veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png"
    },
    {
        "id":4,
        "nombre":"charmander",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png"
    },
    {
        "id":5,
        "nombre":"charmeleon",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png"
    },
    {
        "id":6,
        "nombre":"charizard",
        "tipo":["fuego", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png"
    },
    {
        "id":7,
        "nombre":"squirtle",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png"
    },
    {
        "id":8,
        "nombre":"wartortle",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png"
    },
    {
        "id":9,
        "nombre":"blastoise",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png"
    },
    {
        "id":10,
        "nombre":"caterpie",
        "tipo":["bicho"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png"
    },
    {
        "id":11,
        "nombre":"metapod",
        "tipo":["bicho"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/011.png"
    },
    {
        "id":12,
        "nombre":"butterfree",
        "tipo":["bicho", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png"
    },
    {
        "id":13,
        "nombre":"weedle",
        "tipo":["bicho", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png"
    },
    {
        "id":14,
        "nombre":"kakuna",
        "tipo":["bicho", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/014.png"
    },
    {
        "id":15,
        "nombre":"beedrill",
        "tipo":["bicho", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/015.png"
    },
    {
        "id":16,
        "nombre":"pidgey",
        "tipo":["normal", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png"
    },
    {
        "id":17,
        "nombre":"pidgeotto",
        "tipo":["normal", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/017.png"
    },
    {
        "id":18,
        "nombre":"pidgeot",
        "tipo":["normal", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/018.png"
    },
    {
        "id":19,
        "nombre":"rattata",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png"
    },
    {
        "id":20,
        "nombre":"raticate",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/020.png"
    },
    {
        "id":21,
        "nombre":"spearow",
        "tipo":["normal", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png"
    },
    {
        "id":22,
        "nombre":"fearow",
        "tipo":["normal", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/022.png"
    },
    {
        "id":23,
        "nombre":"ekans",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png"
    },
    {
        "id":24,
        "nombre":"arbok",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/024.png"
    },
    {
        "id":25,
        "nombre":"pikachu",
        "tipo":["electrico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png"
    },
    {
        "id":26,
        "nombre":"raichu",
        "tipo":["electrico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/026.png"
    },
    {
        "id":27,
        "nombre":"sandshrew",
        "tipo":["tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png"
    },
    {
        "id":28,
        "nombre":"sandslash",
        "tipo":["tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/028.png"
    },
    {
        "id":29,
        "nombre":"nidoran♀",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/029.png"
    },
    {
        "id":30,
        "nombre":"nidorina",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/030.png"
    },
    {
        "id":31,
        "nombre":"nidoqueen",
        "tipo":["veneno", "tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/031.png"
    },
    {
        "id":32,
        "nombre":"nidoran♂",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/032.png"
    },
    {
        "id":33,
        "nombre":"nidorino",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/033.png"
    },
    {
        "id":34,
        "nombre":"nidoking",
        "tipo":["veneno", "tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/034.png"
    },
    {
        "id":35,
        "nombre":"clefairy",
        "tipo":["hada"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png"
    },
    {
        "id":36,
        "nombre":"clefable",
        "tipo":["hada"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/036.png"
    },
    {
        "id":37,
        "nombre":"vulpix",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png"
    },
    {
        "id":38,
        "nombre":"ninetales",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/038.png"
    },
    {
        "id":39,
        "nombre":"jigglypuff",
        "tipo":["normal","hada"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/039.png"
    },
    {
        "id":40,
        "nombre":"wigglytuff",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/040.png"
    },
    {
        "id":41,
        "nombre":"zubat",
        "tipo":["veneno", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/041.png"
    },
    {
        "id":42,
        "nombre":"golbat",
        "tipo":["veneno", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/042.png"
    },
    {
        "id":43,
        "nombre":"oddish",
        "tipo":["planta", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/043.png"
    },
    {
        "id":44,
        "nombre":"gloom",
        "tipo":["planta", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/044.png"
    },
    {
        "id":45,
        "nombre":"vileplume",
        "tipo":["planta", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/045.png"
    },
    {
        "id":46,
        "nombre":"paras",
        "tipo":["planta", "bicho"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/046.png"
    },
    {
        "id":47,
        "nombre":"parasect",
        "tipo":["planta", "bicho"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/047.png"
    },
    {
        "id":48,
        "nombre":"venonat",
        "tipo":["bicho", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/048.png"
    },
    {
        "id":49,
        "nombre":"venomoth",
        "tipo":["bicho", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/049.png"
    },
    {
        "id":50,
        "nombre":"diglett",
        "tipo":["tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/050.png"
    },
    {
        "id":51,
        "nombre":"dugtrio",
        "tipo":["tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/051.png"
    },
    {
        "id":52,
        "nombre":"meowth",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/052.png"
    },
    {
        "id":53,
        "nombre":"persian",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/053.png"
    },
    {
        "id":54,
        "nombre":"psyduck",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/054.png"
    },
    {
        "id":55,
        "nombre":"golduck",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/055.png"
    },
    {
        "id":56,
        "nombre":"mankey",
        "tipo":["lucha"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/056.png"
    },
    {
        "id":57,
        "nombre":"primeape",
        "tipo":["lucha"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/057.png"
    },
    {
        "id":58,
        "nombre":"growlithe",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/058.png"
    },
    {
        "id":59,
        "nombre":"arcanine",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/059.png"
    },
    {
        "id":60,
        "nombre":"poliwag",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/060.png"
    },
    {
        "id":61,
        "nombre":"poliwhirl",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/061.png"
    },
    {
        "id":62,
        "nombre":"poliwrath",
        "tipo":["agua", "lucha"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/062.png"
    },
    {
        "id":63,
        "nombre":"abra",
        "tipo":["psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/063.png"
    },
    {
        "id":64,
        "nombre":"kadabra",
        "tipo":["psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/064.png"
    },
    {
        "id":65,
        "nombre":"alakazam",
        "tipo":["psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/065.png"
    },
    {
        "id":66,
        "nombre":"machop",
        "tipo":["lucha"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/066.png"
    },
    {
        "id":67,
        "nombre":"machoke",
        "tipo":["lucha"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/067.png"
    },
    {
        "id":68,
        "nombre":"machamp",
        "tipo":["lucha"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/068.png"
    },
    {
        "id":69,
        "nombre":"bellsprout",
        "tipo":["planta", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/069.png"
    },
    {
        "id":70,
        "nombre":"weepinbell",
        "tipo":["planta", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/070.png"
    },
    {
        "id":71,
        "nombre":"victreebel",
        "tipo":["planta", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/071.png"
    },
    {
        "id":72,
        "nombre":"tentacool",
        "tipo":["agua", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/072.png"
    },
    {
        "id":73,
        "nombre":"tentacruel",
        "tipo":["agua", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/073.png"
    },
    {
        "id":74,
        "nombre":"geodude",
        "tipo":["roca", "tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/074.png"
    },
    {
        "id":75,
        "nombre":"graveler",
        "tipo":["roca", "tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/075.png"
    },
    {
        "id":76,
        "nombre":"golem",
        "tipo":["roca", "tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/076.png"
    },
    {
        "id":77,
        "nombre":"ponyta",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/077.png"
    },
    {
        "id":78,
        "nombre":"rapidash",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/078.png"
    },
    {
        "id":79,
        "nombre":"slowpoke",
        "tipo":["agua", "psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/079.png"
    },
    {
        "id":80,
        "nombre":"slowbro",
        "tipo":["agua", "psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/080.png"
    },
    {
        "id":81,
        "nombre":"magnemite",
        "tipo":["electrico", "acero"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/081.png"
    },
    {
        "id":82,
        "nombre":"magneton",
        "tipo":["electrico", "acero"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/082.png"
    },
    {
        "id":83,
        "nombre":"farfetch'd",
        "tipo":["normal", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/083.png"
    },
    {
        "id":84,
        "nombre":"doduo",
        "tipo":["normal", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/084.png"
    },
    {
        "id":85,
        "nombre":"dodrio",
        "tipo":["normal", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/085.png"
    },
    {
        "id":86,
        "nombre":"seel",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/086.png"
    },
    {
        "id":87,
        "nombre":"dewgong",
        "tipo":["agua", "hielo"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/087.png"
    },
    {
        "id":88,
        "nombre":"grimer",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/088.png"
    },
    {
        "id":89,
        "nombre":"muk",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/089.png"
    },
    {
        "id":90,
        "nombre":"shellder",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/090.png"
    },
    {
        "id":91,
        "nombre":"cloyster",
        "tipo":["agua", "hielo"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/091.png"
    },
    {
        "id":92,
        "nombre":"ghastly",
        "tipo":["fantasma", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/092.png"
    },
    {
        "id":93,
        "nombre":"haunter",
        "tipo":["fantasma", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/093.png"
    },
    {
        "id":94,
        "nombre":"gengar",
        "tipo":["fantasma", "veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/094.png"
    },
    {
        "id":95,
        "nombre":"onix",
        "tipo":["roca", "tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/095.png"
    },
    {
        "id":96,
        "nombre":"drowzee",
        "tipo":["psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/096.png"
    },
    {
        "id":97,
        "nombre":"hypno",
        "tipo":["psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/097.png"
    },
    {
        "id":98,
        "nombre":"krabby",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/098.png"
    },
    {
        "id":99,
        "nombre":"kingler",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/099.png"
    },
    {
        "id":100,
        "nombre":"voltorb",
        "tipo":["electrico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/100.png"
    },
    {
        "id":101,
        "nombre":"electrode",
        "tipo":["electrico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/101.png"
    },
    {
        "id":102,
        "nombre":"exeggcute",
        "tipo":["planta", "psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/102.png"
    },
    {
        "id":103,
        "nombre":"exeggutor",
        "tipo":["planta", "psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/103.png"
    },
    {
        "id":104,
        "nombre":"cubone",
        "tipo":["tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/104.png"
    },
    {
        "id":105,
        "nombre":"marowak",
        "tipo":["tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/105.png"
    },
    {
        "id":106,
        "nombre":"hitmonlee",
        "tipo":["lucha"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/106.png"
    },
    {
        "id":107,
        "nombre":"hitmonchan",
        "tipo":["lucha"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/107.png"
    },
    {
        "id":108,
        "nombre":"lickitung",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/108.png"
    },
    {
        "id":109,
        "nombre":"koffing",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/109.png"
    },
    {
        "id":110,
        "nombre":"weezing",
        "tipo":["veneno"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/110.png"
    },
    {
        "id":111,
        "nombre":"rhyhorn",
        "tipo":["roca", "tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/111.png"
    },
    {
        "id":112,
        "nombre":"rhydon",
        "tipo":["roca", "tierra"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/112.png"
    },
    {
        "id":113,
        "nombre":"chansey",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/113.png"
    },
    {
        "id":114,
        "nombre":"tangela",
        "tipo":["planta"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/114.png"
    },
    {
        "id":115,
        "nombre":"kangaskhan",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/115.png"
    },
    {
        "id":116,
        "nombre":"horsea",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/116.png"
    },
    {
        "id":117,
        "nombre":"seadra",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/117.png"
    },
    {
        "id":118,
        "nombre":"goldeen",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/118.png"
    },
    {
        "id":119,
        "nombre":"seaking",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/119.png"
    },
    {
        "id":120,
        "nombre":"staryu",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/120.png"
    },
    {
        "id":121,
        "nombre":"starmie",
        "tipo":["agua", "psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/121.png"
    },
    {
        "id":122,
        "nombre":"mr. Mime",
        "tipo":["hada", "psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/122.png"
    },
    {
        "id":123,
        "nombre":"cyther",
        "tipo":["bicho", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/123.png"
    },
    {
        "id":124,
        "nombre":"jynx",
        "tipo":["hielo", "psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/124.png"
    },
    {
        "id":125,
        "nombre":"electabuzz",
        "tipo":["electrico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/125.png"
    },
    {
        "id":126,
        "nombre":"magmar",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/126.png"
    },
    {
        "id":127,
        "nombre":"pinsir",
        "tipo":["bicho"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/127.png"
    },
    {
        "id":128,
        "nombre":"tauros",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/128.png"
    },
    {
        "id":129,
        "nombre":"magikarp",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/129.png"
    },
    {
        "id":130,
        "nombre":"gyarados",
        "tipo":["agua", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/130.png"
    },
    {
        "id":131,
        "nombre":"lapras",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/131.png"
    },
    {
        "id":132,
        "nombre":"ditto",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/132.png"
    },
    {
        "id":133,
        "nombre":"eevee",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/133.png"
    },
    {
        "id":134,
        "nombre":"vaporeon",
        "tipo":["agua"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/134.png"
    },
    {
        "id":135,
        "nombre":"jolteon",
        "tipo":["electrico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/135.png"
    },
    {
        "id":136,
        "nombre":"flareon",
        "tipo":["fuego"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/136.png"
    },
    {
        "id":137,
        "nombre":"porygon",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/137.png"
    },
    {
        "id":138,
        "nombre":"omanyte",
        "tipo":["agua", "roca"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/138.png"
    },
    {
        "id":139,
        "nombre":"omastar",
        "tipo":["agua", "roca"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/139.png"
    },
    {
        "id":140,
        "nombre":"kabuto",
        "tipo":["agua", "roca"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/140.png"
    },
    {
        "id":141,
        "nombre":"kabutops",
        "tipo":["agua", "roca"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/141.png"
    },
    {
        "id":142,
        "nombre":"aerodactyl",
        "tipo":["volador", "roca"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/142.png"
    },
    {
        "id":143,
        "nombre":"snorlax",
        "tipo":["normal"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/143.png"
    },
    {
        "id":144,
        "nombre":"articuno",
        "tipo":["hielo", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/144.png"
    },
    {
        "id":145,
        "nombre":"zapdos",
        "tipo":["electrico", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/145.png"
    },
    {
        "id":146,
        "nombre":"moltres",
        "tipo":["fuego", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/146.png"
    },
    {
        "id":147,
        "nombre":"dratini",
        "tipo":["dragon"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/147.png"
    },
    {
        "id":148,
        "nombre":"dragonair",
        "tipo":["dragon"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/148.png"
    },
    {
        "id":149,
        "nombre":"dragonite",
        "tipo":["dragon", "volador"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/149.png"
    },
    {
        "id":150,
        "nombre":"mewtwo",
        "tipo":["psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/150.png"
    },
    {
        "id":151,
        "nombre":"mew",
        "tipo":["psiquico"],
        "imgURL":"https://assets.pokemon.com/assets/cms2/img/pokedex/detail/151.png"
    },
];

export default pokedex;